import { NextRequest, NextResponse } from 'next/server';
import { openai } from '@/lib/ai';

export async function POST(request: NextRequest) {
  try {
    const { prompt, productType } = await request.json();

    const systemPrompt = `You are a top sales copywriter who has generated $100M+ in revenue.

User request: "${prompt}"

Product type: "${productType || 'general'}"

Create KILLER sales copy that converts:

**MUST HAVE:**
1. Compelling hook (first 5 seconds)
2. Pain-agitate-solution formula
3. 3-5 irresistible benefits
4. Social proof elements
5. Risk reversal guarantee
6. Strong, urgent CTA
7. Power words throughout
8. Emotional triggers
9. Scarcity/urgency
10. Ready-to-use copy

**Formats to include:**
- Sales page headline + body
- Email subject + body
- Ad copy (FB/Google)
- Product description

Make it so good they CAN'T say no!`;

    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Write the sales copy" }
      ],
      max_tokens: 1800,
      temperature: 0.4,
    });

    const content = completion.choices[0].message.content || 'No response generated.';

    return NextResponse.json({ content });
  } catch (error: any) {
    console.error('AI Sales error:', error);
    return NextResponse.json({ 
      error: 'Failed to generate sales copy. Please try again.',
      content: mockSalesContent(prompt)
    }, { status: 500 });
  }
}

function mockSalesContent(prompt: string): string {
  return `💰 **${prompt.substring(0, 40)} - The Ultimate Game Changer!**

**STOP wasting time - start making money TODAY!**

You know that feeling when customers just browse but never buy?

**Your problem solved in 60 seconds...**

**Introducing [Your Product] - the #1 converting solution:**

✅ **3X your sales overnight**
✅ **80% less refunds** 
✅ **Works on autopilot**
✅ **Proven by 5,000+ customers**

**LIMITED TIME: 97% OFF - Just $47 (was $497!)**

*Only 17 spots left at this price*

👇 **CLAIM YOUR SPOT NOW** 👇

"Best investment ever - ROI day 1!" - John D.

**30-Day Money Back Guarantee**

**Click buy now - thank me later!** 🔥

*Generated by Sartrends AI Sales Copywriter*

**Copy-paste ready for your sales page!**`;
}

