import { NextRequest, NextResponse } from 'next/server';
import { generateAI } from '@/lib/ai';

export async function POST(request: NextRequest) {
  try {
    const { prompt, audience } = await request.json();

    const systemPrompt = `You are a world-class marketing copywriter. Create high-converting marketing content.

User request: "${prompt}"

Target audience: "${audience || 'general'}"

Your output must:
1. Be persuasive and benefit-focused
2. Create urgency and scarcity
3. Include strong call-to-action
4. Use power words and emotional triggers
5. Follow AIDA model (Attention, Interest, Desire, Action)
6. Optimized for conversion (ads, emails, landing pages)
7. Ready to use - no placeholders
8. Professional tone suitable for B2B/B2C

Format as ready-to-use marketing copy with subject lines, headers, body, CTA.`;

    const content = await generateAI(systemPrompt + '\nUser: Create the marketing content');

    return NextResponse.json({ content });
  } catch (error: any) {
    console.error('AI Marketing error:', error);
    return NextResponse.json({ 
      error: 'Failed to generate marketing content. Please try again.',
      content: `🚀 **Marketing Revolutionized!**

**Discover the Game-Changer You've Been Waiting For**

Tired of [common problem]? 

**Introducing [your solution] - the breakthrough solution that:**

✅ [Benefit 1] - 3X faster than competitors  
✅ [Benefit 2] - 80% cost savings  
✅ [Benefit 3] - Proven results in 24 hours  

**Limited Time Offer: 50% OFF First Month!**
*Only 50 spots available this week*

👉 **Get Started Now** [CTA Button]

**Join 10,000+ happy customers who already transformed their business**

"Life-changing!" - Sarah K.

*Generated by Sartrends AI Marketing Generator*

**Ready to copy-paste into your ads/emails!** 🔥`
    }, { status: 500 });
  }
}
