import { NextRequest, NextResponse } from 'next/server';
import { openai } from '@/lib/ai';

export async function POST(request: NextRequest) {
  try {
    const { prompt, keywords } = await request.json();

    const systemPrompt = `You are an expert SEO specialist. Optimize the following content for search engines:

Content to optimize: "${prompt}"

Target keywords: "${keywords || 'general optimization'}"

Requirements:
1. Keep original meaning and length similar
2. Include keywords naturally (2-5%)
3. Improve readability and engagement
4. Add internal linking opportunities
5. Optimize headings and structure
6. Include semantic HTML suggestions
7. Add alt text suggestions for images
8. Improve meta description compatibility
9. Add FAQ schema opportunities
10. Output optimized HTML/markdown ready for web

Make it SEO friendly while keeping it natural and valuable for readers.`;

    const completion = await openai.chat.completions.create({
      model: "gpt-3.5-turbo",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: "Optimize the content" }
      ],
      max_tokens: 2000,
      temperature: 0.3,
    });

    const content = completion.choices[0].message.content || 'No response generated.';

    return NextResponse.json({ content });
  } catch (error: any) {
    console.error('AI SEO error:', error);
    return NextResponse.json({ 
      error: 'Failed to generate SEO content. Please try again.',
      content: mockSEOContent(prompt)
    }, { status: 500 });
  }
}

function mockSEOContent(prompt: string): string {
  return `# SEO Optimized ${prompt.substring(0, 50)}...

## Optimized Content

This is your professionally optimized content for search engines. Key improvements:

**Keywords integrated naturally**
**Improved heading structure**
**Better readability score**
**Mobile-first approach**
**Featured snippet potential**
**Internal linking opportunities**
**Schema markup ready**
**Meta description friendly**

### Key SEO Metrics
- **Keyword density**: Optimal 1.5-2%
- **Readability**: Grade 8
- **Sentiment**: Positive
- **Lighthouse score**: 95+

**Ready to publish! 🚀**

*Generated by Sartrends AI SEO Optimizer*`;
}

